# docker compose up -d
# docker compose stop

services:
  api-auth-mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=teste
      - MYSQL_DATABASE=apicrud
      - MYSQL_ROOT_PASSWORD=teste